### ISSUE TITLE
I find it impossible to delete text boxes and plain boxes. This is not always the case but enough to be frustrating. 

### ISSUE THREAD

**Issue by DennisPolack** [Ginj-capture/Ginj#51] opened 2021-12-16 18:31 UTC
I find it impossible to delete text boxes and plain boxes. This is not always the case but enough to be frustrating. 
As a work around, I just drag the offending object out of the main box.

**Comment by vicnevicne** [comment] 2021-12-16 21:37
Probably a duplicate of issue #37

**Closed** 2021-12-16 21:37 UTC
