### ISSUE TITLE
Ginj is really amazing

### ISSUE THREAD

**Issue by DennisPolack** [Ginj-capture/Ginj#43] opened 2021-05-22 20:54 UTC
I used JING for many years and was very disappointed when it was discontinued. I was delighted to discover GINJ and am very impressed by the way it has evolved. I now use it on a daily basis because of the ease of use. Well done GINJ.

**Comment by vicnevicne** [comment] 2021-05-24 10:27
Thanks for the kind words :-).
I'll close this issue to keep a focus on what needs to be achieved, but I think it is a duplicate of issue #1 (well, sort of), so I'll make it a duplicate ;-)

**Closed by vicnevicne** 2021-05-24 10:27 UTC

**Comment by vicnevicne** [comment] 2021-05-24 10:31
Duplicate of #1
