### ISSUE TITLE
Suggestion. Put the installer exe in an obvious place.

### ISSUE THREAD

**Issue by gfmoore** [Ginj-capture/Ginj#22] opened 2020-08-08 11:33 UTC
I couldn't easily find the exe file, so perhaps put the link to this specific file in the readme??

Great work by the way, well done. :)

**Comment by vicnevicne** [comment] 2020-08-08 13:48
Thanks for the feedback !
Yes, I agree with you. 
Writing the install place in the readme would be a small step, but I'd rather have visible shortcut (plus, it's system dependant and can change if you customize the installer steps)
I'm really wondering why Ginj.exe doesn't show up in Windows start menu by typing a few characters, because I think I did everything needed in the installer config
Now the other obvious place I can think of would be the Desktop, but I wonder if it's not a bit rude for a utility to drop its icon on the Desktop. On the other hand, I could make it optional... What do you think ?

**Comment by gfmoore** [comment] 2020-08-08 14:53
Oh, I'm sorry, no I meant on your githhub page"!! 👍

**Comment by vicnevicne** [comment] 2020-08-08 16:18
Oh, my bad :-) :-D.
There's a link to the global "Releases" folder in the readme, but indeed not to specific file.
The issue is that the filename changes with each release, and theres 99% chance I will forget to update the readme with each release, but I've added a paragraph at the top which should make clear what to download .

(and in the meantime, I've added a "Create desktop shortcut" option in the installer ;-))

Closing, please reopen if you think there's a better way.

**Closed by vicnevicne** 2020-08-08 16:18 UTC
