### ISSUE TITLE
Cumbersome changing the Target File

### ISSUE THREAD

**Issue by DennisPolack** [Ginj-capture/Ginj#54] opened 2021-12-16 18:44 UTC
Cumbersome changing the Target File
I have given up changing the target file and send everything to one Folder and at a later stage copying them to the required Folder.
Surprisingly this is easier than changing the Target File. A possible nice enhancement would be Change target and Revert to Original Target.

**Comment by vicnevicne** [comment] 2021-12-16 21:35
Probably a duplicate of issue #42

**Closed by vicnevicne** 2021-12-16 21:35 UTC
