### ISSUE TITLE
Since the latest update I am getting error messages which cannot be removed or deleted.

### ISSUE THREAD

**Issue by DennisPolack** [Ginj-capture/Ginj#40] opened 2021-05-22 20:44 UTC
The Errors are "Cancellation Requested" and "Determining Target File" - Clicking on the Cancel button probably creates another
"Cancellation Requested" error.

**Comment by vicnevicne** [comment] 2021-05-24 10:13
Probably a duplicate of issue #35

**Closed** 2021-05-24 10:13 UTC
