### ISSUE TITLE
The small squares on the corners of the boxes are too small and difficult to get focus.

### ISSUE THREAD

**Issue by DennisPolack** [Ginj-capture/Ginj#50] opened 2021-12-16 18:28 UTC
Battle to adjust box size. Not a serious problem but irritating.

**Comment by vicnevicne** [comment] 2021-12-16 21:44
Dennis, I'm willing to solve your handling issues, but please comment on the original issues instead of opening new ones.

You seem to be the only one struggling with selection operations (selecting handles, deleting boxes, selecting files and folders) so I guess Java is behaving weirdly on your machine.
I know you said you have the problem on multiple machines, so it's probably linked to a settings you have on all machines (I don't know, some people prefer to have the task bar on top, some people have very high resolutions, some people use screen zooming).
If you have time, could you record a video with your phone showing difficulties you have in handling ?

I could make the handles (small squares on the corner of the boxes) larger (or configurable) but seeing the other issues you're encountering, I guess the problem lies elsewhere.

Kind regards,

Vicne

**Comment by vicnevicne** [comment] 2021-12-16 21:44
Probably a duplicate of issue #38

**Closed by vicnevicne** 2021-12-16 21:44 UTC
