### ISSUE TITLE
After half a dozen screen grabs, ginj sun disappears

### ISSUE THREAD

**Issue by gfmoore** [Ginj-capture/Ginj#33] opened 2021-03-18 12:10 UTC
I've noted this for some time, but just worked around it, however it is now a nuisance.

So I have two screens, I do a screengrab, copy it and paste into word. No issue. I do this about 5 or 6 (maybe more) and then the ginj sun disappear. It's still running in the system tray, but I have to close down (from system tray). This causes a dialog to appear, I close down, and then restart ginj. Everything runs ok.

Sometimes the ginj sun is there but there are no bottom 3 lugs? appearing, the two side lugs are there, but the action of mouseover does nothing except reveal the side lugs.

Still love it though :)

**Comment by vicnevicne** [comment] 2021-03-18 19:47
This really looks like issue #13 so I'm reopening it.

**Comment by gfmoore** [comment] 2021-03-19 09:41
Fine with me :)

**Comment by vicnevicne** [comment] 2021-05-20 09:01
Duplicate of issue #13

**Closed by vicnevicne** 2021-05-20 09:01 UTC
