### ISSUE TITLE
It would be nice if it remembered what mode was used previously.

### ISSUE THREAD

**Issue by DennisPolack** [Ginj-capture/Ginj#52] opened 2021-12-16 18:33 UTC
It would be nice if it remembered what mode was used previously.
It defaults to the arrow which I hardly ever used and definitely use after I have added text to a box.

**Comment by vicnevicne** [comment] 2021-12-16 21:38
Probably a duplicate of issue #39

**Closed by vicnevicne** 2021-12-16 21:38 UTC
