### ISSUE TITLE
Floating  App  can only be placed on Main Display.

### ISSUE THREAD

**Issue by infinitebizmedia** [Ginj-capture/Ginj#6] opened 2020-07-20 16:15 UTC
Floating  App  can only be placed on Main Display. When trying to place on other non secondary display, the app snaps back to farthest right corner of the main display.

**Comment by vicnevicne** [comment] 2020-07-20 19:13
Can you confirm you are using the latest version (v0.3.4) ? You can check the version in the More > About box.
If it is the latest version, can you give me details about your display setup (how many displays, what layout). Something like this display setup :
![image](https://user-images.githubusercontent.com/842233/87976613-b448d580-cacd-11ea-8ff1-fa5a77f39f23.png)
and the resolutions of the different screens ?
If it is not up to date, can you please update and retry ? Thanks.

**Comment by vicnevicne** [comment] 2020-07-21 23:40
Just tested again with version 0.3.5 (just released), and I can't reproduce the issue. 
If you can reproduce it with 0.3.5, could you please provide more information ? Thanks

**Comment by infinitebizmedia** [comment] 2020-07-22 15:40
ok this can be closed. after re-installing 3.5 all my current issue are resolved.

**Comment by vicnevicne** [comment] 2020-07-22 15:41
Great. Thanks for confirming.
Closing.

**Closed by vicnevicne** 2020-07-22 15:41 UTC
Labels: help wanted
